### ISSUE TITLE
Criar o arquivo minhaPagina.html e adicionar o seguinte texto no body do arquivo

### ISSUE THREAD

**Issue by nonilton** [nonilton/curso_git#9]
De onde ele vem?
Ao contrário do que se acredita, Lorem Ipsum não é simplesmente um texto randômico. Com mais de 2000 anos, suas raízes podem ser encontradas em uma obra de literatura latina clássica datada de 45 AC. Richard McClintock, um professor de latim do Hampden-Sydney College na Virginia, pesquisou uma das mais obscuras palavras em latim, consectetur, oriunda de uma passagem de Lorem Ipsum, e, procurando por entre citações da palavra na literatura clássica, descobriu a sua indubitável origem. Lorem Ipsum vem das seções 1.10.32 e 1.10.33 do "de Finibus Bonorum et Malorum" (Os Extremos do Bem e do Mal), de Cícero, escrito em 45 AC. Este livro é um tratado de teoria da ética muito popular na época da Renascença. A primeira linha de Lorem Ipsum, "Lorem Ipsum dolor sit amet..." vem de uma linha na seção 1.10.32.

**Comment by AlexTayron** [comment]
## Icaro
Crie corretamente um titulo

```
<h1>Aqui é o Titulo</h1>
```

**Comment by icaroweb0** [comment]
Alteração feita, vou subir o PR
